# Generated by Django 4.2.7 on 2023-12-01 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=2500),
        ),
    ]
