# Generated by Django 4.2.7 on 2023-12-02 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0004_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
