# Generated by Django 4.2.7 on 2023-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0005_rename_skills_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="small_description",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
