# Generated by Django 4.2.7 on 2023-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0007_technology"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="project",
        ),
        migrations.RemoveField(
            model_name="technology",
            name="project",
        ),
        migrations.AddField(
            model_name="skill",
            name="project",
            field=models.ManyToManyField(to="pf.project"),
        ),
        migrations.AddField(
            model_name="technology",
            name="project",
            field=models.ManyToManyField(to="pf.project"),
        ),
    ]
