# Generated by Django 4.2.7 on 2023-12-02 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0008_remove_skill_project_remove_technology_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="url",
            new_name="github",
        ),
    ]
