# Generated by Django 4.2.7 on 2023-12-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0010_project_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(blank=True, upload_to="project_images/")),
                ("project", models.ManyToManyField(to="pf.project")),
            ],
        ),
    ]
