# Generated by Django 4.2.7 on 2023-12-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0011_remove_project_image_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, upload_to="project_images/"),
        ),
    ]
