# Generated by Django 4.2.7 on 2024-01-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0013_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
