# Generated by Django 4.2.7 on 2024-01-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='media/media/'),
        ),
    ]
