# Generated by Django 4.2.7 on 2024-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0017_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(default='', max_length=240),
        ),
    ]
