# Generated by Django 4.2.7 on 2024-01-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pf", "0018_userprofile_github_userprofile_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(blank=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(default="", max_length=2500),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="", max_length=50),
        ),
    ]
